In [1]:
import numpy as np
another = np.array([[11,12,13],[21,22,23],[31,41,45]])
print(another)

[[11 12 13]
 [21 22 23]
 [31 41 45]]


In [2]:
another[1,2]

23

In [3]:
print(another.shape)

(3, 3)


In [4]:
print(another[0],another[1],another[2])

[11 12 13] [21 22 23] [31 41 45]


In [5]:
another[0],another[1]=77,44
print(another)

[[77 77 77]
 [44 44 44]
 [31 41 45]]


In [6]:
another = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(another)
print(another[0,0],another[0,1],another[0,2],another[0,3])

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
11 12 13 14


In [7]:
ex1=np.zeros((3,3))
print(ex1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
ex2=np.full((4,3),10)
print(ex2)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


In [9]:
ex3=np.eye(6,4)  #it increment 1 & never decrement
print(ex3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ex4=np.ones((5,5))  #it comes only 1 in every index
print(ex4)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
print(ex4.shape)
print(ex4[0,0])

(5, 5)
1.0


In [12]:
ex5=np.random.random((2,2))
print(ex5)

[[0.50003585 0.98953709]
 [0.34032137 0.36237091]]


# Array Indexing

In [13]:
another = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(another)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [14]:
print(another[1:3,1:3])

[[22 23]
 [32 33]]


In [15]:
print(another[:,1:3])

[[12 13]
 [22 23]
 [32 33]]


In [16]:
print(another[0,:])

[11 12 13 14]


In [17]:
new=np.array([[2,3,4,6,7,8,9],[2,3,4,6,7,8,9]])
print(new)

[[2 3 4 6 7 8 9]
 [2 3 4 6 7 8 9]]


In [18]:
print(new[:2,2:4])

[[4 6]
 [4 6]]


In [19]:
print(new[0,:])

[2 3 4 6 7 8 9]


In [20]:
print(new[:2,3:6])

[[6 7 8]
 [6 7 8]]


In [21]:
print(new[:2,1:5])

[[3 4 6 7]
 [3 4 6 7]]


In [22]:
a_slice1=another[0:3,0:2]
print(a_slice1)

[[11 12]
 [21 22]
 [31 32]]


In [23]:
print (another[0,2])

13


In [24]:
print("Before:" , another[0,1])
a_slice1[0,0]=950
print("After:",a_slice1[0,0])

Before: 12
After: 950


In [25]:
another = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(another)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [26]:
import numpy as np     
row_rank1=another[2]  #if it is vector then it will come [] # else [] []
print(row_rank1 , row_rank1.shape)  #also we can remove the colon(:) for getting the exact o/p

[31 32 33 34] (4,)


In [27]:
import numpy as np     
row_rank2=another[1:2,:]  #if it is vector then it will come [] # else [] []
print(row_rank2 , row_rank2.shape) #1 row, 4 columnsk1=another[]

[[21 22 23 24]] (1, 4)


In [28]:
col_rank1=another[:,0]
print(col_rank1 , col_rank1.shape)

[11 21 31] (3,)


In [29]:
col_rank2=another[:,1:2]
print(col_rank2 , col_rank2.shape)

[[12]
 [22]
 [32]] (3, 1)


In [30]:
another = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34],[41,42,43,44]])
print('original array')
print(another)

original array
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [31]:
col_indices=np.array([0,1,2,2])     ##doubt
print('\ncol indices picked:' , col_indices)

row_indices=np.arange(4)   ## may be it shows store like arranging like here it stored 0 name in 0 index 
print('\nrows indices picked:',row_indices)


col indices picked: [0 1 2 2]

rows indices picked: [0 1 2 3]


In [32]:
for row,col in zip(row_indices,col_indices):
    print(row,",", col)

0 , 0
1 , 1
2 , 2
3 , 2


In [33]:
print('values in the array at those indices:' ,another[row_indices,col_indices])

values in the array at those indices: [11 22 33 43]


In [34]:
another[row_indices,col_indices]+=100
print('\nchanged array:')
print(another)


changed array:
[[111  12  13  14]
 [ 21 122  23  24]
 [ 31  32 133  34]
 [ 41  42 143  44]]


# Boolean Indexing

In [35]:
another=np.array([[11,12],[21,22],[31,32]])
print(another)

[[11 12]
 [21 22]
 [31 32]]


In [36]:
filter=(another>20)  ##if we use array with condition then it will show T/F
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [37]:
print(another[filter])  ##if we use filter within condition then it will show numeric value

[21 22 31 32]


In [38]:
another[another>20]

array([21, 22, 31, 32])

In [39]:
another[another %2==0]+=100  ##if ist is even no or it can divide by 2 then it will come with +=result
print(another)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# Data Type

In [40]:
ex1=np.array([32,43,34])
print(ex1.dtype)

int32


In [41]:
ex2=np.array([27.0 , 32.0])
print(ex2.dtype)

float64


In [42]:
ex3=np.array([11.5,6.5] , dtype=np.int32)  ## we can tell which is float and int
print(ex3.dtype)

int32


In [43]:
ex4=np.array([11,120],dtype=np.float64)
print(ex4.dtype)
print(ex4)

float64
[ 11. 120.]


In [44]:
ex5=np.array([11,87],dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 87.]


# Arithmetic Array Operations:

In [45]:
x=np.array([[12,13] , [20,30]] , dtype=np.int32)
y=np.array([[10.0,40.0] , [18.0,14.0]], dtype=np.float64)

print(x)
print()
print(y)

[[12 13]
 [20 30]]

[[10. 40.]
 [18. 14.]]


In [46]:
print(x+y)
print()
print(np.add(x,y))

[[22. 53.]
 [38. 44.]]

[[22. 53.]
 [38. 44.]]


In [47]:
print(x-y)
print()
print(np.subtract(x,y))

[[  2. -27.]
 [  2.  16.]]

[[  2. -27.]
 [  2.  16.]]


In [48]:
print(x*y)
print()
print(np.multiply(x,y))

[[120. 520.]
 [360. 420.]]

[[120. 520.]
 [360. 420.]]


In [49]:
print(x/y)
print()
print(np.divide(x,y))

[[1.2        0.325     ]
 [1.11111111 2.14285714]]

[[1.2        0.325     ]
 [1.11111111 2.14285714]]


In [50]:
print(np.sqrt(x))

[[3.46410162 3.60555128]
 [4.47213595 5.47722558]]


In [51]:
print(np.exp(x))    ##exp?

[[1.62754791e+05 4.42413392e+05]
 [4.85165195e+08 1.06864746e+13]]


# Statistical Methods,Sorting , and Set Operations:

In [52]:
arr=10*np.random.randn(2,5)
print(arr)

[[ 7.04700883 -0.80150193  6.25024279 -3.39844741  7.00078595]
 [-6.62923518  4.70269659  3.08965707 -4.0321148   0.85529266]]


In [53]:
print(arr.mean())

1.40843845654627


In [54]:
print(arr.mean(axis=1))

[ 3.21961765 -0.40274073]


In [55]:
print(arr.mean(axis=0))

[ 0.20888683  1.95059733  4.66994993 -3.71528111  3.9280393 ]


In [56]:
print(arr.sum())

14.0843845654627


In [57]:
print(np.median(arr , axis=1))

[6.25024279 0.85529266]


# Sorting:

In [58]:
lst=[3,6,7,6,3,3]
set(lst)

{3, 6, 7}

In [59]:
unsorted=np.random.randn(10)
print(unsorted)

[-1.43579     0.0898147   0.02742483 -0.57762324  0.98107401 -1.29934903
  0.00446338  0.45079836 -1.31927184 -0.04827398]


In [60]:
sorted=np.array(unsorted)
sorted.sort()

print(sorted)
print()
print(unsorted)

[-1.43579    -1.31927184 -1.29934903 -0.57762324 -0.04827398  0.00446338
  0.02742483  0.0898147   0.45079836  0.98107401]

[-1.43579     0.0898147   0.02742483 -0.57762324  0.98107401 -1.29934903
  0.00446338  0.45079836 -1.31927184 -0.04827398]


In [61]:
unsorted.sort()
print(unsorted)

[-1.43579    -1.31927184 -1.29934903 -0.57762324 -0.04827398  0.00446338
  0.02742483  0.0898147   0.45079836  0.98107401]


In [62]:
array=np.array([3,6,7,6,3,3])
print(np.unique(array))

[3 6 7]


In [63]:
s1=np.array(['desk','chair','bulb'])
s2=np.array(['lamp','bulb','chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [64]:
print(np.intersect1d(s1,s2))

['bulb' 'chair']


In [65]:
print(np.union1d(s1,s2))

['bulb' 'chair' 'desk' 'lamp']


In [66]:
print(np.setdiff1d(s2,s1))

['lamp']


In [67]:
print(np.in1d(s1,s2))

[False  True  True]


# Broadcasting

In [68]:
import numpy as np

start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [69]:
add_rows=np.array([1,0,2])
print(add_rows)

[1 0 2]


In [70]:
y=start+add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [71]:
add_cols=np.array([[0,1,2,3]])
add_cols=add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [72]:
y=start+add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [73]:
add_scalar=np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [74]:
arrA=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arrA)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
arrB=[0,1,0,2]
print(arrB)

[0, 1, 0, 2]


In [76]:
print(arrA+arrB)

[[ 1  3  3  6]
 [ 5  7  7 10]
 [ 9 11 11 14]]


# speedtest

In [77]:
from numpy import arange
from timeit import Timer

size=1000000
timeits=1000

In [78]:
nd_array=arange(size)
print(type(nd_array))

<class 'numpy.ndarray'>


In [79]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))


Time taken by numpy ndarray: 0.000389 seconds


In [80]:
a_list = list(range(size))
print (type(a_list) )


<class 'list'>


In [81]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))


Time taken by list:  0.018625 seconds


# Read or Write to Disk:


# Binary Format:



In [82]:
x = np.array([ 23.23, 24.24] )


In [83]:
np.save('an_array', x)


In [84]:
np.load('an_array.npy')


array([23.23, 24.24])

# Text Format:



In [85]:
np.savetxt('array.txt', X=x, delimiter=',')


In [86]:
!cat array.txt


'cat' is not recognized as an internal or external command,
operable program or batch file.


In [87]:
np.loadtxt('array.txt', delimiter=',')


array([23.23, 24.24])

# Additional Common ndarray Operations


# Dot Product on Matrices and Inner Product on Vectors:



In [88]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d, y2d))


[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [89]:
a1d = np.array([9 , 9 ])
b1d = np.array([10, 10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d, b1d))


180

180


In [90]:
print(x2d.dot(a1d))
print()
print(np.dot(x2d, a1d))


[18 18]

[18 18]


# Sum:



In [91]:
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))

66


In [92]:
print(np.sum(ex1, axis=0))

[32 34]


In [93]:
print(np.sum(ex1, axis=1))

[23 43]


# Element-wise Functions:



# For example, let's compare two arrays values to get the maximum of each.



In [94]:
x = np.random.randn(8)
x


array([ 0.50135657, -0.93986389,  0.68886879, -1.37519556, -0.11193103,
       -0.07547783,  0.0143515 ,  0.0558782 ])

In [95]:
y = np.random.randn(8)
y


array([ 1.09673244, -0.26806262, -1.35857397, -0.24565666, -0.76445371,
        0.22270934, -0.86070164, -1.53828741])

In [117]:
import numpy as np
x = np.random.randn(8)
y = np.random.randn(8)
print (x)
print(y)

np.maximum(x, y)


[-1.12717702  1.23138571  0.60859138  0.01130323 -0.74679532 -1.00573546
 -0.39838565 -0.11741297]
[-0.09751792  0.06463082 -1.03078305 -0.29207519 -0.17649605 -0.4818114
  0.3395349   0.53663713]


array([-0.09751792,  1.23138571,  0.60859138,  0.01130323, -0.17649605,
       -0.4818114 ,  0.3395349 ,  0.53663713])

# Reshaping array:



In [97]:
arr = np.arange(20)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [98]:
arr.reshape(4,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [119]:
new=np.arange(10)
print(new)

[0 1 2 3 4 5 6 7 8 9]


In [121]:
new.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Transpose:



In [122]:
ex1 = np.array([[11,12,13],[21,22,23]])

ex1.T


array([[11, 21],
       [12, 22],
       [13, 23]])

# Indexing using where():



In [126]:
x_1 = np.array([1,2,3,4,5])

y_1 = np.array([11,22,33,44,55])

filter = np.array([True, True, True, False, True])


In [127]:
out = np.where(filter, x_1, y_1)
print(out)


[ 1  2  3 44  5]


In [102]:
mat = np.random.rand(5,5)
mat


array([[0.62586573, 0.67020183, 0.77504922, 0.46260798, 0.21772608],
       [0.73129787, 0.79568653, 0.53294447, 0.84435866, 0.99201084],
       [0.54262417, 0.28950716, 0.47386395, 0.2989378 , 0.91909769],
       [0.94009301, 0.80429038, 0.89080648, 0.02495783, 0.90554132],
       [0.55487206, 0.82444531, 0.1311086 , 0.62111893, 0.55684616]])

In [103]:
np.where( mat > 0.5, 1000, -1)


array([[1000, 1000, 1000,   -1,   -1],
       [1000, 1000, 1000, 1000, 1000],
       [1000,   -1,   -1,   -1, 1000],
       [1000, 1000, 1000,   -1, 1000],
       [1000, 1000,   -1, 1000, 1000]])

# "any" or "all" conditionals:



In [104]:
arr_bools = np.array([ True, False, True, True, False ])


In [105]:
arr_bools.any()


True

In [106]:
arr_bools.all()


False

# Random Number Generation:



In [107]:
import numpy as np
Y = np.random.normal(size = (1,5))[0]
print(Y)


[ 0.27853661 -0.68090794  0.78215009 -0.98973599  0.21554211]


In [128]:
Z = np.random.randint(low=2,high=50,size=4)
print(Z)


[ 5 21 48 11]


In [131]:
np.random.permutation(Z)

array([ 5, 11, 48, 21])

In [110]:
np.random.uniform(size=4)

array([0.9853899 , 0.76030864, 0.07553579, 0.72339159])

In [111]:
np.random.normal(size=4)

array([-0.0994573 ,  0.91167116, -0.0478158 ,  0.82517798])

# Merging data sets:



In [112]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)


[[40 35]
 [49 17]]

[[14 14]
 [45  3]]


In [113]:
np.vstack((K,M))


array([[40, 35],
       [49, 17],
       [14, 14],
       [45,  3]])

In [114]:
np.hstack((K,M))


array([[40, 35, 14, 14],
       [49, 17, 45,  3]])

In [115]:
np.concatenate([K, M], axis = 0)


array([[40, 35],
       [49, 17],
       [14, 14],
       [45,  3]])

In [116]:
np.concatenate([K, M.T], axis = 1)


array([[40, 35, 14, 45],
       [49, 17, 14,  3]])